<RockSimDocument>
    <FileVersion>4</FileVersion>
    <DesignInformation>
        <RocketDesign>
            <Name>Rocket</Name>
            <StageCount>1</StageCount>
            <DisplayFlags>7</DisplayFlags>
            <ViewType>0</ViewType>
            <ViewStageCount>3</ViewStageCount>
            <ViewTypeEdit>0</ViewTypeEdit>
            <ViewStageCountEdit>3</ViewStageCountEdit>
            <ZoomFactor>0.0</ZoomFactor>
            <ZoomFactorEdit>0.0</ZoomFactorEdit>
            <ScrollPosX>0</ScrollPosX>
            <ScrollPosY>0</ScrollPosY>
            <ScrollPosXEdit>0</ScrollPosXEdit>
            <ScrollPosYEdit>0</ScrollPosYEdit>
            <ThreeDFlags>0</ThreeDFlags>
            <ThreeDFlagsEdit>0</ThreeDFlagsEdit>
            <LastSerialNumber>15</LastSerialNumber>
            <Stage3Mass>0.0</Stage3Mass>
            <Stage2Mass>0.0</Stage2Mass>
            <Stage1Mass>0.0</Stage1Mass>
            <Stage3CG>561.4657523164954</Stage3CG>
            <Stage2CGAlone>0.0</Stage2CGAlone>
            <Stage1CGAlone>0.0</Stage1CGAlone>
            <Stage321CG>0.0</Stage321CG>
            <Stage32CG>0.0</Stage32CG>
            <CPCalcFlags>1</CPCalcFlags>
            <CPSimFlags>1</CPSimFlags>
            <UseKnownMass>0</UseKnownMass>
            <Stage3Parts>
                <NoseCone>
                    <KnownMass>93.52673199916815</KnownMass>
                    <Density>1300.0</Density>
                    <Material>PLA</Material>
                    <Name>Nose cone</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>93.52673199916815</CalcMass>
                    <CalcCG>141.25891687968544</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>180.0</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>1</SerialNo>
                    <ShapeCode>1</ShapeCode>
                    <ConstructionType>1</ConstructionType>
                    <WallThickness>1.9999999999999996</WallThickness>
                    <ShapeParameter>0.0</ShapeParameter>
                    <AttachedParts/>
                    <BaseDia>60.0</BaseDia>
                    <ShoulderLen>10.0</ShoulderLen>
                    <ShoulderOD>60.0</ShoulderOD>
                </NoseCone>
                <BodyTube>
                    <KnownMass>101.1278675190556</KnownMass>
                    <Density>1850.0</Density>
                    <Material>Fiberglass</Material>
                    <Name>Extra tube</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>101.1278675190556</CalcMass>
                    <CalcCG>75.0</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>150.0</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>2</SerialNo>
                    <OD>60.0</OD>
                    <ID>55.99999999999999</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>55.99999999999999</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <Parachute>
                            <KnownMass>100.0</KnownMass>
                            <Density>0.006700000000000001</Density>
                            <Material>Ripstop nylon</Material>
                            <Name>Parachute</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>10.99999999999995</Xb>
                            <CalcMass>215.88670779051614</CalcMass>
                            <CalcCG>62.499999999999986</CalcCG>
                            <DensityType>1</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>124.99999999999997</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>3</SerialNo>
                            <Dia>2000.0</Dia>
                            <ShroudLineCount>6</ShroudLineCount>
                            <Thickness>0.0</Thickness>
                            <ShroudLineLen>500.0</ShroudLineLen>
                            <ChuteCount>1</ChuteCount>
                            <ShroudLineMassPerMM>0.0018</ShroudLineMassPerMM>
                            <ShroudLineMaterial>Elastic cord (round 2 mm, 1/16 in)</ShroudLineMaterial>
                            <DragCoefficient>0.8</DragCoefficient>
                        </Parachute>
                        <MassObject>
                            <KnownMass>20.0</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Shock cord</Name>
                            <KnownCG>4.99999999999991</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>4.99999999999991</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>40.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>4</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                    </AttachedParts>
                </BodyTube>
                <BodyTube>
                    <KnownMass>1452.9866022852796</KnownMass>
                    <Density>1850.0</Density>
                    <Material>Fiberglass</Material>
                    <Name>Body tube</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>1452.9866022852796</CalcMass>
                    <CalcCG>250.0</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>500.0</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>5</SerialNo>
                    <OD>60.0</OD>
                    <ID>39.99999999999999</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>39.99999999999999</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <MassObject>
                            <KnownMass>250.0</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Flight Control</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>0.0</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>80.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>6</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <Ring>
                            <KnownMass>20.420352248333675</KnownMass>
                            <Density>1300.0</Density>
                            <Material>PLA</Material>
                            <Name>Altimeter block</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>80.0</Xb>
                            <CalcMass>20.420352248333675</CalcMass>
                            <CalcCG>5.000000000000004</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>10.000000000000009</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>7</SerialNo>
                            <OD>60.0</OD>
                            <ID>40.0</ID>
                            <UsageCode>2</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <BodyTube>
                            <KnownMass>84.41773619461142</KnownMass>
                            <Density>1300.0</Density>
                            <Material>PLA</Material>
                            <Name>Electronics bay</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>180.0</Xb>
                            <CalcMass>84.41773619461142</CalcMass>
                            <CalcCG>65.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>130.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>8</SerialNo>
                            <OD>55.99999999999999</OD>
                            <ID>49.999999999999986</ID>
                            <IsMotorMount>0</IsMotorMount>
                            <MotorDia>49.999999999999986</MotorDia>
                            <EngineOverhang>0.0</EngineOverhang>
                            <IsInsideTube>1</IsInsideTube>
                            <AttachedParts/>
                        </BodyTube>
                        <MassObject>
                            <KnownMass>800.0</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Flight computer</Name>
                            <KnownCG>185.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>185.0</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>120.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>9</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <LaunchLug>
                            <KnownMass>1.1026990214100176</KnownMass>
                            <Density>1300.0</Density>
                            <Material>PLA</Material>
                            <Name>Launch lug</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>235.0</Xb>
                            <CalcMass>1.1026990214100176</CalcMass>
                            <CalcCG>15.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>30.0</Len>
                            <FinishCode>2</FinishCode>
                            <SerialNo>10</SerialNo>
                            <OD>10.0</OD>
                            <ID>8.0</ID>
                        </LaunchLug>
                    </AttachedParts>
                </BodyTube>
                <BodyTube>
                    <KnownMass>168.54644586509258</KnownMass>
                    <Density>1850.0</Density>
                    <Material>Fiberglass</Material>
                    <Name>Tail</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>168.54644586509258</CalcMass>
                    <CalcCG>125.0</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>250.0</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>11</SerialNo>
                    <OD>60.0</OD>
                    <ID>55.99999999999999</ID>
                    <IsMotorMount>1</IsMotorMount>
                    <MotorDia>55.99999999999999</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <FinSet>
                            <KnownMass>47.17500000000001</KnownMass>
                            <Density>1850.0</Density>
                            <Material>Fiberglass</Material>
                            <Name>Trapezoidal fin set</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>47.17500000000001</CalcMass>
                            <CalcCG>69.83934639050345</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>2</FinishCode>
                            <SerialNo>12</SerialNo>
                            <FinCount>3</FinCount>
                            <RootChord>120.00000000000004</RootChord>
                            <TipChord>50.000000000000014</TipChord>
                            <SemiSpan>49.99999999999999</SemiSpan>
                            <SweepDistance>57.80939390525793</SweepDistance>
                            <Thickness>2.0</Thickness>
                            <ShapeCode>0</ShapeCode>
                            <TipShapeCode>0</TipShapeCode>
                            <TabLength>50.0</TabLength>
                            <TabDepth>0.0</TabDepth>
                            <TabOffset>0.0</TabOffset>
                            <SweepMode>1</SweepMode>
                            <CantAngle>0.0</CantAngle>
                        </FinSet>
                        <Ring>
                            <KnownMass>21.955962737408328</KnownMass>
                            <Density>1300.0</Density>
                            <Material>PLA</Material>
                            <Name>Centering ring</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>60.00000000000005</Xb>
                            <CalcMass>21.955962737408328</CalcMass>
                            <CalcCG>6.999999999999999</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>13.999999999999998</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>13</SerialNo>
                            <OD>55.99999999999999</OD>
                            <ID>40.00000000000001</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Ring>
                            <KnownMass>9.09114082095813</KnownMass>
                            <Density>1300.0</Density>
                            <Material>PLA</Material>
                            <Name>Centering ring</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>16.0</Xb>
                            <CalcMass>9.09114082095813</CalcMass>
                            <CalcCG>6.999999999999999</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>13.999999999999998</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>14</SerialNo>
                            <OD>55.99999999999999</OD>
                            <ID>50.0</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Ring>
                            <KnownMass>37.573448136933926</KnownMass>
                            <Density>1300.0</Density>
                            <Material>PLA</Material>
                            <Name>Engine block</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>101.0</Xb>
                            <CalcMass>37.573448136933926</CalcMass>
                            <CalcCG>10.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>20.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>15</SerialNo>
                            <OD>55.99999999999999</OD>
                            <ID>35.99999999999999</ID>
                            <UsageCode>2</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                    </AttachedParts>
                </BodyTube>
            </Stage3Parts>
            <Stage2Parts/>
            <Stage1Parts/>
        </RocketDesign>
    </DesignInformation>
</RockSimDocument>